### ISSUE TITLE
Crear gráficas para funciones generales

### ISSUE THREAD

**Issue by Navarreteed** [Navarreteed/Optimizacion_Simmulated_Annealing#3]
Gráficar Alkey, coseno una parabola y visualizar las aproximaciones SA

**Comment by CAMM961001** [comment]
@Navarreteed  @BrandonHT se incorporan visualizaciones de las funciones implementadas por @BrandonHT 

Quedo en espera de comentarios

**Comment by Navarreteed** [comment]
Uff te quedaron geniales. Que bueno que usamos el consejo de Ezequiel para visualizar las aproximaciones.
