### ISSUE TITLE
Gráficas para problema del agente viajero

### ISSUE THREAD

**Issue by Navarreteed** [Navarreteed/Optimizacion_Simmulated_Annealing#4]

**Comment by CAMM961001** [comment]
@Navarreteed @BrandonHT se incorporan visualizaciones de las funciones propuestas por @BrandonHT

**Comment by CAMM961001** [comment]
Se vuelve a abrir el Issue porque me equivoqué...

**Comment by CAMM961001** [comment]
@Navarreteed @BrandonHT se cargan visualizaciones del problema del agente viajero para la primera versión del reporte
